[package]
name = "sort_uniq_c"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
is-terminal = "0.4.12"
cli-table = "0.4.7"
itertools = "0.13.0"
